# The port to run the webserver on. Please make sure this is unique across all applications.
LOCAL_PORT: 5000

# Port to run OAuth callback webserver. Please make sure this is unique across all applications.
OAUTH_PORT: 17563

# Create a Twitch application here: https://dev.twitch.tv/console/apps/create
# (Twitch will complain if you don't have 2-Factor Authentication enabled though)
# Set the OAuth Redirect URL to http://localhost:17563 (use the right port as specified above)
CLIENT_ID: 12345
CLIENT_SECRET: abcde

# Twitch user id. Use https://codepen.io/Alca/full/RwaredM to get yours.
USER_ID: 123456

# According to Twitch documentation you shouldn't run stuff more than 800 times a minute (that's 13.33 times per second)
# However due to caching, making it lower than 2 is a bit useless.
POLL_FREQUENCY: 3

# How long to keep a finished poll up. Set to `null` to disable.
INACTIVE_COUNT: 30

# Never caches twitch oauth, if it keeps breaking or whatever.
NEVER_CACHE_TWITCH: false

# Debug mode. Set to true for testing purposes.
DEBUG: false